(() => {
  "use strict";

  function getElements(documentRef) {
    const root = documentRef || (typeof document !== "undefined" ? document : null);
    if (!root) throw new Error("A document object is required to collect Budget Board elements.");
    return {
    board: root.getElementById("board"),
    boardMeta: root.getElementById("boardMeta"),
    deleteAllBtn: root.getElementById("deleteAllBtn"),
    importXlsxBtn: root.getElementById("importXlsxBtn"),
    summaryBtn: root.getElementById("summaryBtn"),
    allPlannedBtn: root.getElementById("allPlannedBtn"),
    restoreBtn: root.getElementById("restoreBtn"),
    exportBtn: root.getElementById("exportBtn"),
    addColumnBtn: root.getElementById("addColumnBtn"),
    xlsxInput: root.getElementById("xlsxInput"),
    backupInput: root.getElementById("backupInput"),
    expenseDialog: root.getElementById("expenseDialog"),
    expenseForm: root.getElementById("expenseForm"),
    expenseDialogTitle: root.getElementById("expenseDialogTitle"),
    expenseId: root.getElementById("expenseId"),
    expenseDate: root.getElementById("expenseDate"),
    expenseCard: root.getElementById("expenseCard"),
    expenseDescription: root.getElementById("expenseDescription"),
    expenseNote: root.getElementById("expenseNote"),
    expenseOriginalCategory: root.getElementById("expenseOriginalCategory"),
    expenseColumn: root.getElementById("expenseColumn"),
    expensePlannedMatch: root.getElementById("expensePlannedMatch"),
    expenseAmount: root.getElementById("expenseAmount"),
    expenseCurrency: root.getElementById("expenseCurrency"),
    expenseInitialAmount: root.getElementById("expenseInitialAmount"),
    expenseInitialCurrency: root.getElementById("expenseInitialCurrency"),
    expenseRemainingAmount: root.getElementById("expenseRemainingAmount"),
    expenseRemainingCurrency: root.getElementById("expenseRemainingCurrency"),
    splitExpenseDialog: root.getElementById("splitExpenseDialog"),
    splitExpenseForm: root.getElementById("splitExpenseForm"),
    splitSourceExpenseId: root.getElementById("splitSourceExpenseId"),
    splitSourceSummary: root.getElementById("splitSourceSummary"),
    splitDescription: root.getElementById("splitDescription"),
    splitInitialBasisOption: root.getElementById("splitInitialBasisOption"),
    splitPlainCurrency: root.getElementById("splitPlainCurrency"),
    splitInitialCurrency: root.getElementById("splitInitialCurrency"),
    splitPlainAmount: root.getElementById("splitPlainAmount"),
    splitInitialAmount: root.getElementById("splitInitialAmount"),
    splitAmountHelp: root.getElementById("splitAmountHelp"),
    splitPreview: root.getElementById("splitPreview"),
    mergeExpenseDialog: root.getElementById("mergeExpenseDialog"),
    mergeExpenseForm: root.getElementById("mergeExpenseForm"),
    mergeParentExpenseId: root.getElementById("mergeParentExpenseId"),
    mergeParentSummary: root.getElementById("mergeParentSummary"),
    mergeChildList: root.getElementById("mergeChildList"),
    mergeSelectAllBtn: root.getElementById("mergeSelectAllBtn"),
    mergeClearSelectionBtn: root.getElementById("mergeClearSelectionBtn"),
    mergePlannedMatch: root.getElementById("mergePlannedMatch"),
    mergePreview: root.getElementById("mergePreview"),
    columnDialog: root.getElementById("columnDialog"),
    columnForm: root.getElementById("columnForm"),
    columnDialogTitle: root.getElementById("columnDialogTitle"),
    columnId: root.getElementById("columnId"),
    columnTitle: root.getElementById("columnTitle"),
    columnColor: root.getElementById("columnColor"),
    columnColorText: root.getElementById("columnColorText"),
    columnIcon: root.getElementById("columnIcon"),
    columnIconPreview: root.getElementById("columnIconPreview"),
    colorPalette: root.getElementById("colorPalette"),
    sortDialog: root.getElementById("sortDialog"),
    sortForm: root.getElementById("sortForm"),
    sortColumnId: root.getElementById("sortColumnId"),
    maskDialog: root.getElementById("maskDialog"),
    maskForm: root.getElementById("maskForm"),
    maskPattern: root.getElementById("maskPattern"),
    maskTargetColumn: root.getElementById("maskTargetColumn"),
    maskPreview: root.getElementById("maskPreview"),
    bulkLabelDialog: root.getElementById("bulkLabelDialog"),
    bulkLabelForm: root.getElementById("bulkLabelForm"),
    bulkLabelColumnId: root.getElementById("bulkLabelColumnId"),
    bulkLabelDescription: root.getElementById("bulkLabelDescription"),
    goalDialog: root.getElementById("goalDialog"),
    goalForm: root.getElementById("goalForm"),
    goalDialogTitle: root.getElementById("goalDialogTitle"),
    goalColumnId: root.getElementById("goalColumnId"),
    goalCurrency: root.getElementById("goalCurrency"),
    goalSharePercent: root.getElementById("goalSharePercent"),
    goalAmountLimit: root.getElementById("goalAmountLimit"),
    goalPreview: root.getElementById("goalPreview"),
    clearGoalBtn: root.getElementById("clearGoalBtn"),
    summaryDialog: root.getElementById("summaryDialog"),
    summaryContent: root.getElementById("summaryContent"),
    allPlannedDialog: root.getElementById("allPlannedDialog"),
    allPlannedContent: root.getElementById("allPlannedContent"),
    plannedDialog: root.getElementById("plannedDialog"),
    plannedDialogTitle: root.getElementById("plannedDialogTitle"),
    plannedColumnId: root.getElementById("plannedColumnId"),
    plannedOverview: root.getElementById("plannedOverview"),
    plannedList: root.getElementById("plannedList"),
    addPlannedBtn: root.getElementById("addPlannedBtn"),
    plannedEditDialog: root.getElementById("plannedEditDialog"),
    plannedForm: root.getElementById("plannedForm"),
    plannedEditTitle: root.getElementById("plannedEditTitle"),
    plannedId: root.getElementById("plannedId"),
    plannedEditColumnId: root.getElementById("plannedEditColumnId"),
    plannedSourceExpenseId: root.getElementById("plannedSourceExpenseId"),
    plannedDescription: root.getElementById("plannedDescription"),
    plannedTitleHelp: root.getElementById("plannedTitleHelp"),
    plannedSourceInfo: root.getElementById("plannedSourceInfo"),
    plannedAmount1: root.getElementById("plannedAmount1"),
    plannedCurrency1: root.getElementById("plannedCurrency1"),
    plannedAmount2: root.getElementById("plannedAmount2"),
    plannedCurrency2: root.getElementById("plannedCurrency2"),
    plannedClosed: root.getElementById("plannedClosed"),
    plannedMatchDialog: root.getElementById("plannedMatchDialog"),
    plannedMatchForm: root.getElementById("plannedMatchForm"),
    plannedMatchTitle: root.getElementById("plannedMatchTitle"),
    plannedMatchId: root.getElementById("plannedMatchId"),
    plannedMatchExpense: root.getElementById("plannedMatchExpense"),
    plannedMatchExpenseCards: root.getElementById("plannedMatchExpenseCards"),
    plannedMatchPreview: root.getElementById("plannedMatchPreview"),
    unmatchPlannedBtn: root.getElementById("unmatchPlannedBtn"),
    importDialog: root.getElementById("importDialog"),
    chooseXlsxBtn: root.getElementById("chooseXlsxBtn"),
    toastRegion: root.getElementById("toastRegion")
  };

  }

  const api = Object.freeze({ getElements });

  if (typeof window !== "undefined") window.BudgetBoardDom = api;
  if (typeof module !== "undefined" && module.exports) module.exports = api;
})();
